skip_undocumented: false
objc: true
clean: true
author: Moblico LLC
author_url: http://moblico.com
github_url: https://github.com/Moblico/MoblicoSDK-iOS
sdk: iphonesimulator
module: MoblicoSDK
framework_root: .
module_version: 1.8
copyright: © 2017 Moblico LLC
umbrella_header: MoblicoSDK/MoblicoSDK.h
documentation: Guides/*.md
